config/routes.rb
Rails.application.routes.draw do

  #rake routes --> para ver las rutas
  resources :tracks
  resources :playlists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base

    validates_presence_of :name, :number_of_votes
end

app/models/track.rb
class Track < ApplicationRecord

  validates_presence_of :title, :artist, :album
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  def index
    @playlists = Playlist.all  ##Obtener todas las listas de reproduccioon
  end

  def show
    @playlists = Playlist.find(params[:id])
  end

  def new
    @playlists = Playlist.new
  end

  def create
    @playlists = Playlist.new(playlist_params)
    if @playlists.save
      redirect_to @playlists
    else
      render :new
    end
  end

  private

  def playlist_params
    params.require(:playlist).permit(:name, :number_of_votes)
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:title, :album, :artist)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/playlists/index.html.erb
<h2>Playlist</h2>

<table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Number of votes</th>
        </tr>
      </thead>
      <tbody>
        <% @playlists.each do |playlist|%>
          <tr>
            <td> <%= playlist.name %></td>
            <td> <%= playlist.number_of_votes%></td>
          </tr>
         <% end %>
      </tbody>
</table>

app/views/playlists/new.html.erb
<%= form_for(@playlists) do |f|%>

    <%= f.label :name%>
    <%= f.text_field :name%>

    <%= f.label :number_of_votes%>
    <%= f.text_field :number_of_votes%>

    <%= f.submit%>
<% end %>

app/views/playlists/show.html.erb

<p>
  <strong> Name: </strong>
  <%= @playlists.name%>
</p>

<p>
  <strong> Number of votes: </strong>
  <%= @playlists.number_of_votes%>
</p>

app/views/tracks/_form.html.erb
<%= form_with(model: track, local: true) do |form| %>
  <% if track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :track_title %>
  </div>

  <div class="field">
    <%= form.label :album %>
    <%= form.text_field :album, id: :track_album %>
  </div>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist, id: :track_artist %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing Track</h1>

<%= render 'form', track: @track %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tracks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Album</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= track.title %></td>
        <td><%= track.album %></td>
        <td><%= track.artist %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Edit', edit_track_path(track) %></td>
        <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Track', new_track_path %>

app/views/tracks/new.html.erb
<h1>New Track</h1>

<%= render 'form', track: @track %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @track.title %>
</p>

<p>
  <strong>Album:</strong>
  <%= @track.album %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @track.artist %>
</p>

<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>